package:
  name: cyclus
  version: 0.4

source:
  #fn: develop.zip # [linux]
  #url: https://github.com/cyclus/cyclus/archive/develop.zip # [linux]
  git_url: https://github.com/cyclus/cyclus.git 
requirements:
   build:
    - sigcpp
    - glibmm
    - libxmlpp 
    - coincbc
    - boost
    - hdf5
    - mylibxml2 # [osx]
    - libxml2  #  [linux]
    - myglib   # [osx]  
    - cmake
    - libffi # [osx]
    - gettext # [osx]
    - pkg-config-lite # [osx]
   run:
    - sigcpp
    - glibmm
    - libxmlpp
    - coincbc
    - boost
    - hdf5
    - libxml2 # [not osx]
    - mylibxml2 # [osx]


build:
  number: 2            [osx]

about:
  home: Cyclus
  license: Eclipse Public License 1.0
