package:
  name: cyclus
  version: 0.0

source:
  fn: cyclus-src.tar.gz 
  url: https://github.com/cyclus/cyclus/archive/develop.tar.gz 

requirements:
   build:
    - sigcpp
    - glibmm
    - libxmlpp 
    - coincbc
    - boost
    - hdf5
    - mylibxml2 # [osx]
    - libxml2  #  [linux]
    - myglib   # [osx]  
    - libffi # [osx]
    - gettext # [osx]
    - pkg-config-lite # [osx]
    - cmake
    - python
   run:
    - sigcpp
    - glibmm
    - libxmlpp
    - coincbc
    - boost
    - hdf5
    - mylibxml2 # [osx]
    - libxml2  #  [linux]
    - myglib   # [osx]  
    - libffi # [osx]
    - gettext # [osx]
    - pkg-config-lite # [osx]

build:
  string: nightly

about:
  home: Cyclus
  license: BSD Clause 3
