package:
  name: cyclus
  version: 0.0

source:
  fn: develop.tar.gz # [linux and environ.get('NMI_PLATFORM', False)]
  url: https://github.com/cyclus/cyclus/archive/develop.tar.gz # [linux and environ.get('NMI_PLATFORM', False)]
  git_url: https://github.com/cyclus/cyclus.git # [not (linux and environ.get('NMI_PLATFORM', False))]
  git_tag: develop # [not (linux and environ.get('NMI_PLATFORM', False))]

requirements:
   build:
    - sigcpp
    - glibmm
    - libxmlpp 
    - coincbc
    - boost
    - hdf5
    - mylibxml2 # [osx]
    - libxml2  #  [linux]
    - myglib   # [osx]  
    - libffi # [osx]
    - gettext # [osx]
    - pkg-config-lite # [osx]
    - cmake
    - python
   run:
    - sigcpp
    - glibmm
    - libxmlpp
    - coincbc
    - boost
    - hdf5
    - mylibxml2 # [osx]
    - libxml2  #  [linux]
    - myglib   # [osx]  
    - libffi # [osx]
    - gettext # [osx]
    - pkg-config-lite # [osx]

build:
  string: nightly

about:
  home: Cyclus
  license: BSD Clause 3
