package:
  name: cyclus
  version: 1.0rc4

source:
  #fn: develop.zip # [linux]
  #url: https://github.com/cyclus/cyclus/archive/develop.zip # [linux]
  git_url: https://github.com/cyclus/cyclus.git 
  git_tag: develop
requirements:
   build:
    - sigcpp
    - glibmm
    - libxmlpp 
    - coincbc
    - boost
    - hdf5
    - mylibxml2 # [osx]
    - libxml2  #  [linux]
    - myglib   # [osx]  
    - libffi # [osx]
    - gettext # [osx]
    - pkg-config-lite # [osx]
    - cmake
    - python
    - numpy
   run:
    - sigcpp
    - glibmm
    - libxmlpp
    - coincbc
    - boost
    - hdf5
    - mylibxml2 # [osx]
    - libxml2  #  [linux]
    - myglib   # [osx]  
    - libffi # [osx]
    - gettext # [osx]
    - pkg-config-lite # [osx]
    - numpy

build:
  number: 2

about:
  home: Cyclus
  license: BSD Clause 3
