package:
  name: cyclist
  version: 0.0

source:
  # keep these commented lines for batlab
  #fn: master.tar.gz
  #url: https://github.com/cyclus/cyclist2/archive/master.tar.gz
  git_url: http://github.com/cyclus/cyclist2.git
  git_tag: master

requirements:
   build:
    - java-jdk
    - ant
   run:
    - java-jre
    - cycamore # [unix]
    - launcher

# If the app key makes this appear in the launcher.
app:
  # The command that is called to launch the app
  entry: cyclist
  #icon: icon64x64.png
  summary: Cyclist is a visual interface companion for the Cyclus project.

about:
  home: Cyclus
  license: BSD 3-Clause
