package:
  name: cyclist
  version: 0.0

source:
  # keep these commented lines for batlab
  #fn: master.tar.gz
  #url: https://github.com/cyclus/cyclist2/archive/master.tar.gz
  git_url: http://github.com/cyclus/cyclist2.git
  git_tag: master

requirements:
   build:
    - java-jdk
    - ant
   run:
    - java-jre
    - cycamore # [unix]

build:
  number: 1
  string: test

about:
  home: Cyclus
  license: BSD 3-Clause
