package:
  name: java-jre
  version: 8.20.26

# Cannot use source section because of cookies blocking download
#source:
#  fn: jre-8u20-linux-x64.tar.gz
#  url: http://download.oracle.com/otn-pub/java/jdk/8u20-b26/jre-8u20-linux-x64.tar.gz

requirements:
  build:
    - curl [win]
  
about:
  home: http://www.java.com/en/
  license: Oracle Binary Code License Agreement for the Java SE Platform Products and JavaFX
