package:
  name: cymetric
  version: 0.0

source:
  fn: master.zip # [linux and __import__('os').getenv('NMI_PLATFORM')]
  url: https://github.com/cyclus/cymetric/archive/master.zip # [linux and __import__('os').getenv('NMI_PLATFORM')]
  git_url: https://github.com/cyclus/cymetric.git # [not (linux and __import__('os').getenv('NMI_PLATFORM'))]
  git_tag: master # [not (linux and __import__('os').getenv('NMI_PLATFORM'))]

requirements:
   build:
    - cyclus
    - cmake
    - python
    - jinja2
    - cython
    - sigcpp
    - glibmm
    - libxmlpp 
    - coincbc
    - boost
    - hdf5
    - mylibxml2 # [osx]
    - libxml2  #  [linux]
    - myglib   # [osx]  
    - libffi # [osx]
    - gettext # [osx]
    - pkg-config-lite # [osx]
   run:
    - cyclus
    - python
    - pandas

build:
  string: nightly

about:
  home: Cymetric
  license: BSD 3 Clause
