package:
  name: ant
  version: 1.9.4

source:
  fn: apache-ant-1.9.4-src.tar.bz2
  url: https://www.apache.org/dist/ant/source/apache-ant-1.9.4-src.tar.bz2
  sha1: cdefb110fd7dcf87d8697af4369fb476c4c36324

build:
  number: 1            [osx]

requirements:
  build:
    - java-jdk
  run:
    - java-jre

about:
  home: http://ant.apache.org/
  license: Apache 2.0
