package:
  name: cycamore
  version: 0.0

source:
  fn: develop.zip # [linux and __import__('os').getenv('NMI_PLATFORM')]
  url: https://github.com/cyclus/cycamore/archive/develop.zip # [linux and __import__('os').getenv('NMI_PLATFORM')]
  git_url: https://github.com/cyclus/cycamore.git # [not (linux and __import__('os').getenv('NMI_PLATFORM'))]
  git_tag: develop # [not (linux and __import__('os').getenv('NMI_PLATFORM'))]

requirements:
   build:
    - cyclus
    - cmake
    - python
   run:
    - cyclus

build:
  string: nightly

about:
  home: Cyclus
  license: BSD 3 Clause
