package:
  name: cycamore
  version: 0.0

# Only use fn and url for polyphemus compatability
source:
  fn: cycamore-src.tar.gz
  url: https://github.com/cyclus/cycamore/archive/develop.tar.gz

requirements:
   build:
    - cyclus
    - cmake
    - python
   run:
    - cyclus

build:
  string: nightly

about:
  home: Cyclus
  license: BSD 3 Clause
