package:
  name: boost
  version: 2.8.7

source:
  fn: boost_1_50_0.tar.gz
  url:  http://sourceforge.net/projects/boost/files/boost/1.50.0/boost_1_50_0.tar.gz

build:
  number: 2            [osx]

about:
  home: Boost
  license: Eclipse Public License 1.0
